from __future__ import annotations

from typing import TYPE_CHECKING, Optional, Protocol

from laffyhand.core.domain.messages import Message

if TYPE_CHECKING:
    from laffyhand.core.session.models import Session
    from laffyhand.core.session.todo.models import TodoItem
    from laffyhand.core.models.tag import FileTag


class SessionRepository(Protocol):
    def insert(self, session: Session) -> None: ...
    def get(self, session_id: str) -> Optional[Session]: ...
    def get_active(self) -> Optional[Session]: ...
    def list_sessions(
        self, status: Optional[str] = None, limit: int = 20, offset: int = 0
    ) -> list[Session]: ...
    def update(self, session: Session) -> None: ...
    def complete(self, session_id: str) -> None: ...
    def archive(self, session_id: str) -> None: ...
    def delete(self, session_id: str) -> None: ...
    def set_title(self, session_id: str, title: str) -> None: ...
    def update_counters(
        self,
        session_id: str,
        *,
        turn_count: int = 0,
        step_count: int = 0,
        input_tokens: int = 0,
        output_tokens: int = 0,
        reasoning_tokens: int = 0,
        cache_read_tokens: int = 0,
        cache_write_tokens: int = 0,
        message_count: int = 0,
    ) -> None: ...
    def get_depth(self, session_id: str, max_depth: int = 1000) -> int: ...
    def search(self, query: str, limit: int = 20) -> list[Session]: ...
    def get_parent(self, session_id: str) -> Optional[str]: ...
    def get_children(self, session_id: str) -> list[Session]: ...
    def get_compression_tip(self, session_id: str) -> str: ...
    def chain(self, session_id: str) -> list[str]: ...


class MessageRepository(Protocol):
    def insert(self, message: Message, session_id: str) -> None: ...
    def get_by_session(
        self, session_id: str, offset: int = 0, limit: Optional[int] = None
    ) -> list[Message]: ...
    def count_by_session(self, session_id: str) -> int: ...


class TodoRepository(Protocol):
    def insert(self, item: TodoItem) -> None: ...
    def get(self, task_id: str) -> Optional[TodoItem]: ...
    def get_by_session_and_id(self, session_id: str, task_id: str) -> Optional[TodoItem]: ...
    def get_by_session(self, session_id: str, status: Optional[str] = None) -> list[TodoItem]: ...
    def update(self, item: TodoItem) -> None: ...
    def delete(self, task_id: str) -> bool: ...
    def get_dependents(self, task_id: str) -> list[tuple[str, list[str]]]: ...
    def count_by_session(self, session_id: str) -> int: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def touch_session(self, session_id: str) -> None: ...


class FileTagRepository(Protocol):
    def upsert(self, path: str, content: str = "") -> None: ...
    def get(self, path: str) -> Optional[FileTag]: ...
    def list_by_prefix(self, prefix: str) -> list[FileTag]: ...
    def list_all(self) -> list[FileTag]: ...
    def delete(self, path: str) -> bool: ...
    def commit(self) -> None: ...
